/** Map normalized form -> canonical normalized name for lookup. */
export const INGREDIENT_SYNONYMS: Record<string, string> = {
  "all-purpose flour": "all purpose flour",
  "all purpose flour": "all purpose flour",
  "ap flour": "all purpose flour",
  "granulated sugar": "sugar",
  "white sugar": "sugar",
  "caster sugar": "sugar",
  "brown sugar": "light brown sugar",
  "packed brown sugar": "light brown sugar",
  "confectioners sugar": "powdered sugar",
  "powdered sugar": "powdered sugar",
  "icing sugar": "powdered sugar",
  "kosher salt": "salt",
  "sea salt": "salt",
  "fine sea salt": "salt",
  "table salt": "salt",
  "extra virgin olive oil": "olive oil",
  "evoo": "olive oil",
  "olive oil": "olive oil",
  "vanilla extract": "vanilla extract",
  "vanilla": "vanilla extract",
  "large eggs": "eggs",
  "eggs": "eggs",
};
