/** Words to strip from the end (or middle) of ingredient phrases when normalizing. */
export const INGREDIENT_STOPWORDS = new Set([
  "optional",
  "to taste",
  "as needed",
  "for garnish",
  "divided",
  "room temperature",
  "softened",
  "melted",
  "cooled",
  "warmed",
  "diced",
  "minced",
  "chopped",
  "sliced",
  "grated",
  "crushed",
  "fresh",
  "dried",
  "frozen",
  "canned",
  "packed",
  "large",
  "small",
  "medium",
  "whole",
  "halved",
  "peeled",
  "trimmed",
  "thinly",
  "finely",
  "roughly",
  "roughly chopped",
  "cloves",
  "clove",
  "stalks",
  "stalk",
  "pieces",
  "piece",
  "cups",
  "cup",
  "tablespoons",
  "tablespoon",
  "teaspoons",
  "teaspoon",
  "ounces",
  "ounce",
  "grams",
  "pounds",
  "pinch",
]);

/** Words to remove from anywhere in the normalized name (conjunctions/noise that don't identify the ingredient). */
export const NORMALIZE_REMOVE_WORDS = new Set([
  "or",
  "and",
  "at",
  "box",
]);

/** Common leading descriptor words to strip when normalizing. */
export const LEADING_DESCRIPTORS = new Set([
  "organic", "raw", "pure", "unsalted", "salted", "low-fat", "full-fat",
  "nonfat", "reduced-sodium", "extra-virgin", "virgin",
]);
